#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM phusion/baseimage:latest

MAINTAINER Veselin Stoyanov <stoyanov.veseline@gmail.com>

RUN DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

# Add the "Ruby" ppa
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:brightbox/ruby-ng

#
#--------------------------------------------------------------------------
# Ruby installation
#--------------------------------------------------------------------------
#

# Install "Ruby 2.4.1"
RUN apt-get update && \
    apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        ruby2.4 \
        git \
        vim \
        nano \
        curl \
        sqlite3 \
    && apt-get clean

#
#--------------------------------------------------------------------------
# Bundler
#--------------------------------------------------------------------------
#

# Install "Bundler"
RUN gem install bundler
